// client2/src/routes/(auth)/login/+page.svelte
<script>
  import * as Card from "$lib/components/ui/card";
  import Button from "$lib/components/ui/button/button.svelte";
  import Input from "$lib/components/ui/input/input.svelte";

  let email = "";
  let password = "";

  async function handleSubmit(event) {
    event.preventDefault();
    const response = await fetch("https://api.example.com/signup", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ email, password }),
    });

    if (response.ok) {
      // Handle successful response
      console.log("Sign up successful");
    } else {
      // Handle error response
      console.error("Sign up failed");
    }
  }
</script>

<Card.Root>
  <Card.Header>
    <h3 class="text-xl">Log In</h3>
  </Card.Header>

  <Card.Content>
    <form class="flex flex-col gap-2" on:submit={handleSubmit}>
      <Input
        class="w-72"
        placeholder="Email"
        bind:value={email}
        type="email"
        required
      />
      <Input
        placeholder="Password"
        bind:value={password}
        type="password"
        required
      />
      <Button
        type="submit"
        class="mt-4 bg-slate-800 text-white py-2 px-4 rounded"
      >
        Log in
      </Button>
      <a
        href="/signup"
        class="flex justify-center text-blue-500 hover:underline"
      >
        Or create an account
      </a>
    </form>
  </Card.Content>
</Card.Root>

// apps/client/app/routes/login.tsx
import { apiEndpoints } from '../lib/env'
import { Form, Link } from '@remix-run/react'
import { Label } from '../components/ui/label'
import { Input } from '../components/ui/input'
import { Button } from '../components/ui/button'
import { authenticator } from '../services/auth.server'

import type { ActionFunction } from '@remix-run/node'

const action: ActionFunction = async ({ request }) => {
  const form = await request.formData()
  const email = form.get('email') as string
  const password = form.get('password') as string

  const userLoginRequest = await fetch(apiEndpoints.login, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ email, password }),
  })

  // Stubbed out response from API
  const user = await userLoginRequest.json()
  console.log('Response from API', user)

  return await authenticator.authenticate('form', request, {
    successRedirect: '/',
    failureRedirect: '/failed',
    context: { formData: form },
  })
}

export default function LoginPage() {
  return (
    <div className="flex flex-col min-h-screen items-center justify-center space-y-4 p-4">
      <header className="flex flex-col items-center space-y-2">
        <h1 className="text-xl font-bold tracking-wide">Log In</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Lets get you logged in
        </p>
      </header>
      <Form method="post">
        <div className="rounded-lg border border-gray-200 w-72 p-6 space-y-4">
          <div className="space-y-2 ">
            <Label htmlFor="email">Email</Label>
            <Input
              required
              id="email"
              name="email"
              type="email"
              placeholder="rusty@alcoves.io"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input required id="password" name="password" type="password" />
          </div>
          <Button className="w-full" type="submit">
            Log In
          </Button>
          <div>
            <Link to="/register">
              <Button className="w-full" variant="ghost">
                Or Register
              </Button>
            </Link>
          </div>
        </div>
      </Form>
    </div>
  )
}

export { action }
