// client/src/routes/(auth)/login/+page.svelte
<script>
  import { goto } from "$app/navigation";
  import { PUBLIC_ALCOVES_API_URL } from "$env/static/public";

  let email = "";
  let password = "";
  let errorMessage = "";
  let loading = false;

  let cardTitle = "Let's get logged in";
  let cardAction = "Log In";
  let alternateButtonText = "Or create an account";
  let alternateButtonLink = "/signup";

  async function handleSubmit() {
    loading = true;
    errorMessage = "";

    try {
      const response = await fetch(`${PUBLIC_ALCOVES_API_URL}/api/auth/login`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email, password }),
        credentials: "include",
      });

      if (!response.ok) {
        throw new Error("Network response was not ok");
      }

      const data = await response.json();
      console.log("Login successful:", data);
      goto("/");
    } catch (error) {
      console.error("Login Error:", error);
      errorMessage = "An error occurred during login";
    } finally {
      loading = false;
    }
  }
</script>

<div class="card bg-neutral text-neutral-content w-96">
  <div class="card-body items-center text-center">
    <h2 class="card-title">{cardTitle}</h2>
    <form on:submit|preventDefault={handleSubmit}>
      <div class="mt-2 card-actions justify-center">
        <input
          class="input w-full"
          required
          bind:value={email}
          name="email"
          type="email"
          placeholder="Email"
        />
        <input
          class="input w-full"
          required
          bind:value={password}
          name="password"
          type="password"
          placeholder="Password"
        />
        {#if errorMessage}
          <div class="text-red-500">{errorMessage}</div>
        {/if}
        <button
          class="btn w-full btn-primary mt-4"
          type="submit"
          disabled={loading}
        >
          {cardAction}
        </button>
        <a class="mt-2" href={alternateButtonLink}>{alternateButtonText}</a>
      </div>
    </form>
  </div>
</div>

// apps/client/app/routes/login.tsx
import { apiEndpoints } from '../lib/env'
import { Form, Link } from '@remix-run/react'
import { Label } from '../components/ui/label'
import { Input } from '../components/ui/input'
import { Button } from '../components/ui/button'
import { authenticator } from '../services/auth.server'

import type { ActionFunction } from '@remix-run/node'

const action: ActionFunction = async ({ request }) => {
  const form = await request.formData()
  const email = form.get('email') as string
  const password = form.get('password') as string

  const userLoginRequest = await fetch(apiEndpoints.login, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ email, password }),
  })

  // Stubbed out response from API
  const user = await userLoginRequest.json()
  console.log('Response from API', user)

  return await authenticator.authenticate('form', request, {
    successRedirect: '/',
    failureRedirect: '/failed',
    context: { formData: form },
  })
}

export default function LoginPage() {
  return (
    <div className="flex flex-col min-h-screen items-center justify-center space-y-4 p-4">
      <header className="flex flex-col items-center space-y-2">
        <h1 className="text-xl font-bold tracking-wide">Log In</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Lets get you logged in
        </p>
      </header>
      <Form method="post">
        <div className="rounded-lg border border-gray-200 w-72 p-6 space-y-4">
          <div className="space-y-2 ">
            <Label htmlFor="email">Email</Label>
            <Input
              required
              id="email"
              name="email"
              type="email"
              placeholder="rusty@alcoves.io"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input required id="password" name="password" type="password" />
          </div>
          <Button className="w-full" type="submit">
            Log In
          </Button>
          <div>
            <Link to="/register">
              <Button className="w-full" variant="ghost">
                Or Register
              </Button>
            </Link>
          </div>
        </div>
      </Form>
    </div>
  )
}

export { action }
